export const paragraphs = [
  "Você pode me auxiliar? Preciso encontrar uma resposta...",
  "Deixe eu lhe contar uma breve história...",
  "Em um jardim, no seu centro, um pequeno broto surgiu...",
  "O Jardineiro trabalhando pelos arredores do jardim...",
  "Percebeu o leve movimento, despertando sua curiosidade, ele começou a cuidar da pequena planta...",
  "E a partir daquele momento, dia após dias, o jardineiro se fez presente...",
  "Zelando daquele pequeno broto, o qual ele mesmo não havia plantado...",
  "Com o passar dos dias, o broto cresceu rápido, se destacando...",
  "Aquele pequeno broto, de maneira determinada, cresceu mais forte e veloz do que qualquer outra...",
  "No dia seguinte ao sair para trabalhar, o jardineiro parou para observar o nascer do sol...",
  "O reflexo do sol, com seu brilho dourado, clareou todo o jardim...",
  "Então, ele percebeu, a pequena planta, florindo...",
  "Um único Girassol, no centro de tudo, refletindo a luz do sol...",
  "A Flor da felicidade, despertou um sorriso no jardineiro sincero, encantado com o amarelo próspero e cheio de vida...",
  "Preencheu seu coração, foi quando ele sentiu que precisava de uma resposta...",
  "Pei Ping Kao, você quer namorar comigo?",
];
