export const paragraphs = [
  "Você pode me auxiliar? Preciso encontrar uma resposta...",
  "Deixe eu lhe contar uma breve história...",
  "Em um jardim, ao seu centro, um pequeno broto surgiu...",
  "O Jardineiro trabalhando pelos arredores...",
  "Percebeu o leve movimento, despertando sua curiosidade...",
  "Pois ele não lembrava de ter plantado naquele local, mas decidiu cuidar assim mesmo...",
  "Zelando daquele pequeno broto, ele passou a trabalhar no centro do seu jardim...",
  "Zelando dia após dias, observando...",
  "Com o passar do tempo, o broto vem crescendo rápidamente, e se destacando...",
  "Aquele pequeno broto, de maneira determinada, ficando mais forte do que qualquer outro...",
  "Até que um dia, ao sair cedo para trabalhar, o jardineiro decidiu observar o nascer do sol...",
  "O reflexo, brilhando dourado, clareou todo o jardim...",
  "Nesse momento então, ele percebeu, o pequeno broto o qual vem cuidadando, agora florindo...",
  "Um único Girassol, no centro de tudo, refletindo a luz do sol...",
  "A Flor da felicidade, despertando um sorriso sincero, colorindo com o amarelo próspero e cheio de vida...",
  "Preencheu seu coração, foi quando ele sentiu que precisava de uma resposta...",
  "Pei Ping Kao, você quer namorar comigo?",
];
