export const paragraphs = [
  "Você pode me auxiliar? Preciso encontrar uma resposta...",
  "Deixe eu lhe contar uma breve história...",
  "Em um jardim, ao seu centro, um pequeno broto surgiu...",
  "O Jardineiro trabalhando pelos arredores do jardim...",
  "Percebeu o leve movimento, despertando sua curiosidade...",
  "Pois ele não lembrava de ter plantado naquele local, mas decidiu cuidar...",
  "Zelando daquele pequeno broto, o jardineiro passou a focar no centro do seu jardim...",
  "Zelando dia após dias, observando...",
  "Com o passar do tempo, o broto vem crescendo, e se destacando...",
  "Aquele pequeno broto, de maneira determinada, cresceu mais forte e veloz do que qualquer outro...",
  "No dia seguinte ao sair para trabalhar, o jardineiro parou para observar o nascer do sol...",
  "O reflexo do sol, com seu brilho dourado, clareou todo o jardim...",
  "Então, ele percebeu, o pequeno broto, agora florindo...",
  "Um único Girassol, no centro de tudo, refletindo a luz do sol...",
  "A Flor da felicidade, despertou um sorriso no jardineiro sincero, encantado com o amarelo próspero e cheio de vida...",
  "Preencheu seu coração, foi quando ele sentiu que precisava de uma resposta...",
  "Pei Ping Kao, você quer namorar comigo?",
];
